" set encoding=utf-8 set nocompatible                  " Must come first because it changes other options.

syntax enable
filetype plugin indent on    " required

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

" turn off search highlight"
nnoremap <leader><space> :nohlsearch<CR>

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title
set lazyredraw                    " redraw only when we need to."
set showmatch                     " highlight matching [{()}]"

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set tabstop=2
set shiftwidth=2
set expandtab
set number

if !has("gui_running")            " Don't set titleold
set titleold=
if &term == "xterm" && &t_ts == ""
  let &t_ts = "\e]2;"
endif
if &t_ts != ""
  set title titlestring=%t%m\ -\ VIM
endif
endif

set noerrorbells                      " No beeping.
set novisualbell                      " No flashing

set nobackup                          " Don't make a backup before overwriting a file.
set nowritebackup                     " And again.

set directory=$HOME/.vim-tmp/tmp      " Keep swap files in one location
set backupdir=$HOME/.vim-tmp/_backup  " where to put backup files.
 
set tabstop=2                         " Global tab width.
set shiftwidth=2                      " And again, related.
set expandtab                         " Use spaces instead of tabs
set laststatus=2                      " Show the status line all the time
set listchars=tab:▸\ ,eol:¬
"set list                             " Show invisible characters
"set cursorline                       " Show cursor line.  

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.scssc,*.sassc

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/syntastic' " Syntax checker
Plugin 'Shougo/vimproc', { 'do': 'make' }
Plugin 'wincent/ferret', { 'on': ['Ack', 'Acks'] }
Plugin 'ctrlpvim/ctrlp.vim', { 'on': 'CtrlP' } " Full path fuzzy file, buffer, mr    u, tag, finder for Vim
Plugin 'scrooloose/nerdtree' " A tree explorer
Plugin 'ervandew/supertab' " Perform all your vim insert mode completions with Ta    b
Plugin 'godlygeek/tabular' " text filtering and alignment
Plugin 'bling/vim-airline' " lean & mean status/tabline for vim that's light as a    ir
Plugin 'tpope/vim-commentary', { 'tag': 'v1.3' } " comment stuff out
Plugin 'tpope/vim-endwise' " wisely add 'end' in ruby, endfunction/endif/more
Plugin 'plasticboy/vim-markdown' " Markdown Vim Mode
Plugin 'xolox/vim-misc' " Miscellaneous auto-load Vim scripts
Plugin 'xolox/vim-notes' " Easy note taking in Vim
Plugin 'xolox/vim-session' " Extended session management for Vim
Plugin 'airblade/vim-gitgutter' " A Vim plugin which shows a git diff in the sign    -column
Plugin 'mhinz/vim-startify' " A fancy start screen for Vim.
Plugin 'tpope/vim-surround' " quoting/parenthesizing made simple
Plugin 'mattn/webapi-vim' " vim interface to Web API
Plugin 'vim-scripts/argtextobj.vim' " Text-object like motion for arguments
Plugin 'kana/vim-textobj-user' " Create your own text objects
Plugin 'nelstrom/vim-textobj-rubyblock', { 'for': 'ruby' }  " A custom text objec    t for selecting ruby blocks.
Plugin 'sheerun/vim-polyglot' " A collection of language packs for Vim.
Plugin 'junkblocker/patchreview-vim' " doing single, multi-patch or diff code rev    iews
Plugin 'codegram/vim-codereview' " GitHub Pull Request-based Code Reviews
Plugin 'moll/vim-bbye' " Delete buffers and close files in Vim without closing yo    ur windows
Plugin 'AndrewRadev/splitjoin.vim' " simplifies the transition between multiline     and single-line code
Plugin 'mileszs/ack.vim' " ack support from vim

Plugin 'flazz/vim-colorschemes'
Plugin 'tpope/vim-vividchalk'

" Unity
Plugin 'OmniSharp/omnisharp-vim:'
Plugin 'Valloric/YouCompleteMe'
call vundle#end()

" Or use vividchalk
set t_Co=256
colorscheme molokai
highlight clear SignColumn

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_checkers = ['cpp']

" easier navigation between split windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" open buffer files and open one by pressing number + intro
nnoremap <Leader>b :ls<CR>:b

" Map leader to ,
let mapleader=","

" Aliases for some typos
command WQ wq
command Wq wq
command W w
c
